### ISSUE TITLE
Combine rows representing the same record not working with only label show in the header

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#6]
Hi Adam,

When setting the option below as "Label" (in the original "Additional report options")
the "Combine rows representing the same record" will not combine together the rows.

![image](https://user-images.githubusercontent.com/75424115/162991150-e5865fb9-025c-4269-9734-38d637e7e668.png)

![image](https://user-images.githubusercontent.com/75424115/162991237-044a2d90-99c8-4a1a-8896-1bd3ef97ce5e.png)

best
Thomas

**Comment by aanunez** [comment]
Confirmed as bug. Currently we pull the alias of record_id and use that field name to find the correct column without regard to if only the label is displayed. This also impacts the build of `coreColumnMap` in js.

**Comment by aanunez** [comment]
This bug has been resolved in the most recent commit. A release will not be published for another week or two as the most recent version of Redcap has also introduced some display issue with drop downs on the reports page and edit page.

**Comment by ThomasVermes** [comment]
Hello Adam,
unfortunately I have still the same behaviour also with this new version (1.1.3)
Any Idea why?
![image](https://user-images.githubusercontent.com/75424115/172321371-d59d6c02-55c3-4081-a907-de262f763369.png)
![image](https://user-images.githubusercontent.com/75424115/172322642-8718f6dd-be5c-4942-9b51-5d5bb07e9ce1.png)
![image](https://user-images.githubusercontent.com/75424115/172322229-5aa00776-3635-4cfc-9e21-c88546416cc8.png)

REDCap 12.4.1 · PHP 7.4.20 (Windows OS) · MySQL 8.0.11

thanks a lot
Thomas

**Comment by aanunez** [comment]
Reopening issue.

After re-reviewing this issue it appears there were still two problems.

* Column sorting with no field name in the table header didn't behave as expected
* Some reports still weren't merging as expected

I've already released a new version of the module v1.1.4 as a fix, but I will leave this open until we confirm that it has been resolved for you. If you do still have a problem after taking the next version (which should be available from Vanderbilt in a day or two) then please respond with an XML of the project you are using and some example data for the report. 

Thanks

**Comment by aanunez** [comment]
@ThomasVermes the EM's bug fix release was just approved by Vanderbilt and is now available for install.

**Comment by ThomasVermes** [comment]
Dear Adam, now it works, that's great, thanks a lot!

**Comment by aanunez** [comment]
Great, sorry for the delay in the fix.
